# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('aluser', '0002_auto_20191202_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='\ub4f1\ub85d\ub0a0\uc9dc')),
                ('quantity', models.IntegerField(verbose_name='\uc218\ub7c9')),
                ('aluser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluser.Aluser', verbose_name='\uc0ac\uc6a9\uc790')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\uc0c1\ud488')),
            ],
            options={
                'db_table': 'albatross9_order',
                'verbose_name': '\uc8fc\ubb38',
                'verbose_name_plural': '\uc8fc\ubb38\ub4e4',
            },
        ),
    ]
