# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='\uc774\uba54\uc77c')),
                ('password', models.CharField(max_length=64, verbose_name='\ube44\ubc88')),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='\ub4f1\ub85d\uc77c')),
            ],
            options={
                'db_table': 'albatross9_aluser',
                'verbose_name': '\uc0ac\uc6a9\uc790',
                'verbose_name_plural': '\uc0ac\uc6a9\uc790',
            },
        ),
    ]
