# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluser',
            options={'verbose_name': '\uc0ac\uc6a9\uc790', 'verbose_name_plural': '\uc0ac\uc6a9\uc790\ub4e4'},
        ),
    ]
